name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake SVG (Cyberpunk Theme + Background)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: joseloc16
          outputs: |
            dist/github-snake.svg?color_snake=%23ff00ff&color_dots=%2300ffff,%23ff00ff,%238a2be2,%2339ff14&color_background=%230A0A23
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23ff00ff&color_dots=%2300ffff,%23ff00ff,%238a2be2,%2339ff14&color_background=%230A0A23

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
